name: SoundTrek
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  record: ^5.0.5
  audio_streamer: ^4.1.1
  fftea: ^1.5.0
  fluttertoast: ^8.2.5
  geofence_service: ^5.0.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.0
  flutter_map_heatmap: ^0.0.7
  syncfusion_flutter_charts: ^25.2.5
  http: ^1.2.1
  flutter_secure_storage: ^4.2.0
  jwt_decoder: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/

flutter_native_splash:
  image: lib/assets/images/logo_no_text.png
  color: "#219EBC"
  image_dark: lib/assets/images/logo_no_text.png
  color_dark: "#219EBC"
  android_12:
    image: lib/assets/images/logo_no_text.png
    icon_background_color: "#219EBC"
    image_dark: lib/assets/images/logo_no_text.png
    icon_background_color_dark: "#219EBC"

